version: '3'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - N8N_ENCRYPTION_KEY=your-secret-encryption-key
      - NODE_ENV=production
      - WEBHOOK_URL=http://127.0.0.1:5678/
